name: npm install
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup nodes
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    - name: Install
      run: npm install
  
  job2:
    runs-on: ubuntu-latest
    needs: job1    
    steps: 
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup nodes
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    - name: Install
      run: npm install
    - name: Test
      run: npm test